# Generated by Django 5.2.7 on 2025-10-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categories_customerdemographics_customers_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
